### ISSUE TITLE
ERD 다이어그램 작성

### ISSUE THREAD

**Issue by Seungyeup** [imimtu/Brick-Back#8]
기본적인 ERD 다이어그램 작성

* [x] Brick (할 일)
* [x] User (사용자)
* [ ] Hashtag (해쉬테그)

**Comment by Seungyeup** [comment]
@Just-gomin 뼈대 ERD 그려봤는데 피드백 부탁드립니당

- https://github.com/imimtu/Brick-Back/blob/feature/%238-ERD-Diagram/document/Brick_ER_Diagram.drawio.svg

**Comment by Just-gomin** [comment]
### Hash Tag
- 추후 Entity 생성할 때, 사용 빈도 Column이 있으면 좋을 듯.

### User
- OAuth 사용 계획이면, Auth Organization Column 추가해서 인증 기관도 저장하는게 필요 할듯 합니다. 앱에서 인증 진행한 서비스의 아이콘을 띄워 줄 예정.

### ToDo
- 투두 관련 Image 등록이나 Link등록 같은 것도 할 예정인지 논의해볼 필요가 있을 듯.
- 일정 기간마다 반복 설정하는 기능도 추가하고 싶은데, 반복 주기 설정 관련된 Column들도 필요.
    - is_Recursive - boolean
    - recursive_duration - dateTime

**Comment by Seungyeup** [comment]
Hash Tag
- 추후 Entity 생성할 때, 사용 빈도 Column이 있으면 좋을 듯.
 
 ->  HashTag 이건 테이블명이 아니고 Brick 엔티티 안에 칼럼인데..? 뭔가 테이블 명으로 쓴건 아니지?

1. HashTag 랑 아래 사용빈도 칼럼이 필요하다는 말과 연관관계를 모르겠음
2. Brick(일정) 테이블에 사용빈도 칼럼이 필요한 이유는 모르겠음..  todo는 그날 했음/안했음 두가지 케이스만 있는거 아닌지..? 설명이 필요함
3. 인증, image 등록, 반복기능, 알림기능은 전부 동의하고 추후 관련 기능개발시 하나씩 추가합시다!

**Comment by Just-gomin** [comment]
@Seungyeup 

나는 Hash Tag를 따로 테이블로 관리하는게 어떨까 제안해보는거야.

사용자들이 어떤 해시태그로 등록한 일들의 완료율이 어떻게 되는지 시각적으로 파악할 수 있도록?

1. Hash Tag 테이블이 독립적으로 존재
2. 해당 테이블은 사용자가 사용하는 모든 해시태그를 등록
3. Brick의 HashTag 칼럼은 HashTag들의 아이디를 저장

**Comment by Seungyeup** [comment]
아~~ Hashtag 를 따로 테이블로 관리했음 좋겠다는 말이구나 ㅎㅎㅎ 제일 중요한 말을 빼놨노 ㅋㅋㅋㅋ

그럼 Hashtag 테이블은 유저별로 구성되어 master table 형태로 관리되고, 추후 유저가 hashtag 네이밍, 설정등을 변경할 경우,
기존 Brick-table에서 해당 칼럼들을 전부 찾아 update 칠 필요 없이, 1:1 고유아이디로 관리한다. -> 고유아이디에 매핑된 hashtag table 만 관리한다. 이렇게 가시죠!

@Just-gomin  추가로 사용빈도 칼럼 설명도 어떤 느낌인지 부연설명 부탁드립니당

**Comment by Just-gomin** [comment]
@Seungyeup 

음 프로그래머스나 다른 서비스들에서 연말에 통계를 내주는 것 처럼 Brick도 통계를 제시하면 재밌을 것 같아서ㅋㅋ

- "1주일" 동안 가장 많이 쓴 해시태그는 "hash_tag1" 이것 이며, 총 "n"번 사용했습니다
- "hash_tag2"를 사용한 항목은 총 "n1"번 등록되었고, "n2"번 완료 처리가되어 가장 달성율이 높았습니다!

이런식...?ㅎㅎ..

**Comment by Seungyeup** [comment]
@Just-gomin 

오우 굳 추후 Hashtag 테이블 만들때 빈도수도 넣어달라는 말이구먼~~ 이해했으 ㅋㅋㅋ
근데 문제의 소지가 있을 수 있다고 생각되는 생각되는부분이 

1) hashtag1,2 ... 이런식으로 hashtag 를 모든 유저 공통으로(master table 형태) 정의하는 경우, 테그 항목에 대한 유저 개인의 커스터마이징은 불가해진다.
2) hashtag table을 주 단위로 읽고 나서 > 이를 집계하고, 다시 빈도 칼럼을 update 해야 한다. ( update치는 배치성 작업이 운영(실시간)테이블에서  주기적으로 돌아야 함 ) > 주단위라 크리티컬하진 않곘지만 이런게 여러개 생기면 운영성능에 악영향

사실 저런 통계치 값을 제시하고자 하면, 굳이 hashtag table 에 칼럼을 만들어서 그걸 업데이트 치지 말고, 통계 집계(조회) 쿼리를 돌려서 결과값을 저장해두는 테이블을 따로 만들어 관리하는게 괜찮을거 같은데 어떤감?
